# Generated by Django 5.2.7 on 2025-10-17 10:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CBTTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('emoji', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MusicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='affirmationcategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='affirmationcategory',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='affirmationtemplate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='backgroundmusic',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='customaffirmation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='genericaffirmation',
            name='author',
        ),
        migrations.RemoveField(
            model_name='genericaffirmation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='genericaffirmation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='meditationsession',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userpreferences',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='yogasession',
            name='created_at',
        ),
        migrations.CreateModel(
            name='CBTSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.TextField()),
                ('automatic_thought', models.TextField()),
                ('emotions', models.TextField()),
                ('evidence_for', models.TextField()),
                ('evidence_against', models.TextField()),
                ('balanced_thought', models.TextField()),
                ('session_duration', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_api.cbttopic')),
            ],
        ),
        migrations.CreateModel(
            name='MusicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracks_played', models.JSONField(default=list)),
                ('mood_change', models.CharField(choices=[('much_better', 'Much Better'), ('a_bit_better', 'A Bit Better'), ('same', 'Same'), ('worse', 'Worse')], max_length=20)),
                ('current_emotion', models.CharField(max_length=50)),
                ('session_duration', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_api.musiccategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_url', models.URLField()),
                ('duration', models.IntegerField(default=0)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='auth_api.musiccategory')),
            ],
        ),
    ]
