# Generated by Django 5.2.7 on 2025-10-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_cbttopic_musiccategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musictrack',
            name='audio_url',
        ),
        migrations.AddField(
            model_name='musictrack',
            name='audio_file',
            field=models.FileField(default='null', upload_to='music_tracks/'),
            preserve_default=False,
        ),
    ]
