# Generated by Django 5.2.7 on 2025-11-26 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0004_disorder_copingmethod_article_roadmapstep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='user123', max_length=100)),
                ('modality', models.CharField(max_length=10)),
                ('emotion', models.CharField(max_length=30)),
                ('confidence', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmotionJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('voice', models.FileField(blank=True, null=True, upload_to='journal/voice/')),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='journal/face/')),
                ('voice_emotion', models.CharField(blank=True, max_length=20)),
                ('text_emotion', models.CharField(blank=True, max_length=20)),
                ('face_emotion', models.CharField(blank=True, max_length=20)),
                ('final_emotion', models.CharField(blank=True, max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
