# Generated by Django 5.2.7 on 2025-12-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0005_emotionlog_emotionjournal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionjournal',
            name='face_emotion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emotionjournal',
            name='final_emotion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emotionjournal',
            name='text_emotion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emotionjournal',
            name='voice_emotion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
