# Generated by Django 5.1 on 2025-12-27 07:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0007_alter_emotionjournal_face_emotion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReflectionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Text Input'), ('choice', 'Multiple Choice')], default='text', max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text="List of options for Multiple Choice e.g. ['Yes', 'No']")),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TherapySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('therapy_type', models.CharField(choices=[('Music', 'Music Therapy'), ('Drawing', 'Drawing Therapy')], max_length=20)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='therapy_music/')),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds (for music)')),
                ('prompt_text', models.TextField(blank=True, help_text='Prompt for guided drawing', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='therapy_thumbnails/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='meditationsession',
            name='guidance_text',
            field=models.TextField(blank=True, help_text='Text to display on screen during meditation', null=True),
        ),
        migrations.AddField(
            model_name='meditationsession',
            name='image',
            field=models.ImageField(blank=True, help_text='Background Image for the session', null=True, upload_to='meditation_bg/'),
        ),
        migrations.AddField(
            model_name='yogasession',
            name='channel_name',
            field=models.CharField(blank=True, help_text='YouTube Channel Name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='yogasession',
            name='image',
            field=models.ImageField(blank=True, help_text='Custom Thumbnail Image', null=True, upload_to='yoga_thumbnails/'),
        ),
        migrations.AddField(
            model_name='yogasession',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube Video URL', null=True),
        ),
        migrations.CreateModel(
            name='TherapyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_before', models.CharField(blank=True, max_length=50, null=True)),
                ('mood_after', models.CharField(blank=True, max_length=50, null=True)),
                ('drawing_file', models.ImageField(blank=True, null=True, upload_to='user_drawings/')),
                ('reflection_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapy_records', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_api.therapysession')),
            ],
        ),
        migrations.CreateModel(
            name='TherapyRecordAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_api.reflectionquestion')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='auth_api.therapyrecord')),
            ],
        ),
        migrations.AddField(
            model_name='reflectionquestion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='auth_api.therapysession'),
        ),
    ]
