# Generated by Django 5.2.7 on 2025-12-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0008_reflectionquestion_therapysession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawingTherapySession',
            fields=[
            ],
            options={
                'verbose_name': 'Drawing Therapy Session',
                'verbose_name_plural': 'Drawing Therapy Sessions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth_api.therapysession',),
        ),
        migrations.CreateModel(
            name='MusicTherapySession',
            fields=[
            ],
            options={
                'verbose_name': 'Music Therapy Session',
                'verbose_name_plural': 'Music Therapy Sessions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth_api.therapysession',),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
    ]
