# Generated by Django 5.2.7 on 2026-01-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0009_drawingtherapysession_musictherapysession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtsession',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
