# Generated by Django 5.2.7 on 2026-01-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0010_cbtsession_ai_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='disorder',
            name='roadmap_image',
            field=models.ImageField(blank=True, null=True, upload_to='disorder_roadmaps/'),
        ),
        migrations.AddField(
            model_name='roadmapstep',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='roadmap_steps/'),
        ),
    ]
