# Generated by Django 5.0.3 on 2026-01-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0011_disorder_roadmap_image_roadmapstep_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='streak_count',
            field=models.IntegerField(default=0),
        ),
    ]
